### ISSUE TITLE
reproduce test performance metrics

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#128]
reproduce test results for @dckc to perform analysis on.

Ref: #111

**Comment by dckc** [comment]
I don't know whether this issue is critical, but...

for background:

I loaded [the Nov 15 data](https://github.com/hindley-milner-systems/dapp-ertp-airdrop/issues/111#issuecomment-2479820290) into [a spreadsheet](https://docs.google.com/spreadsheets/d/1jD4dsH3BsZ01h3Pn4qGm1NA6SCbDkO2fViF6Zw8T0UQ/edit?usp=sharing)

It looks like the data for scenarios 1 and 3 are the same. I suspect some copy/paste problem.

<details><summary>Code in the spreadsheet for loading the data:</summary>

```js
const loadSheet = (io={}) => {
  const {
    doc = SpreadsheetApp.getActive(),
    sheetName = 'offers',
    sheet = doc.getSheetByName(sheetName)
  } = io;
  const hd = Object.keys({
    s1: 1, s2:1, s3:1,
    })
  const latency = {
    s1: scenario_one.map(({ endTime, startTime}) => endTime - startTime),
    s2: scenario_two.map(({ endTime, startTime}) => endTime - startTime),
    s3: scenario_three.map(({ endTime, startTime}) => endTime - startTime),
  };
  const nRows = max(Object.values(latency).map(a => a.length))
  const rows = []
  for (let rn = 0; rn < nRows; rn++) {
    const row = [latency.s1[rn], latency.s2[rn], latency.s3[rn]]
    rows.push(row)
  }
  setRange(sheet, hd, rows)
}

function setRange(sheet, hd, rows, hdRow = 1, detailRow = hdRow + 1) {
  sheet.getRange(hdRow, 1, 1, hd.length).setValues([hd]);
  sheet.getRange(detailRow, 1, rows.length, hd.length).setValues(rows);
}

const min = xs => xs.reduce((acc, item) => item < acc ? item : acc)
const max = xs => xs.reduce((acc, item) => item > acc ? item : acc)
```

</details>

**Comment by otoole-brendan** [comment]
@tgrecojs I'm interpreting this ticket as the one that is tracking your open Xnet perf testing per previously discussed. Let me know if that's not the case. Please post all test results here for OpCo review when known - ideally ASAP so it doesn't become a long pole for release.

**Comment by tgrecojs** [comment]
this was initially from a conversation dan and I had regarding the local test metrics. I'm going to close this issue and create a new ticket for this task now @otoole-brendan
