### ISSUE TITLE
add offer filter for pausing contract

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#86]

**Comment by tgrecojs** [comment]
pause method is added in PR #99 

### implementation
https://github.com/hindley-milner-systems/dapp-ertp-airdrop/blob/86b493d6bb10fe0f82e1070d1f240feae32e7340/contract/src/airdrop/airdropKitCreator.js#L335-L337


### test code

https://github.com/hindley-milner-systems/dapp-ertp-airdrop/blob/86b493d6bb10fe0f82e1070d1f240feae32e7340/contract/test/tribbles-airdrop/contract.test.js#L199-L233

**Comment by tgrecojs** [comment]
@dckc added references to code above. pinging you for the 👍 before closing.

**Comment by dckc** [comment]
It's hard for me to advise, since #99 isn't green in ci (#57). I checked [a recent ci log](https://github.com/hindley-milner-systems/dapp-ertp-airdrop/actions/runs/10713214885/job/29704895292?pr=99) but the test name **pause method** doesn't occur.

And it would be easier if there were a PR about just this issue, and not all the stuff that's in #99. Then the normal "fixes #86" would automatically close this once the PR is green and merged.

**Comment by tgrecojs** [comment]
closing ... see #109 for remaining tasks.
